indexer dockerfile
econia-labs/econia pull request #320
Opened 2023-07-03 08:41 UTC by qdrs

2023-07-05 10:21 UTC, bogberry requested changes
Steps for adding the `econia_config.json` file need to be added.

2023-07-05 18:26 UTC, alnoki approved these changes

2023-07-06 05:14 UTC, bogberry commented on indexer.Dockerfile
> +    sed -i -e \"s|postgres_uri:.*|postgres_uri: \"${DATABASE_URL}\"|g\" indexer-node.yaml; \
Now that you just have `DATABASE_URL` in the template as of [this commit](https://github.com/econia-labs/aptos-core/pull/10/commits/d0fa1265cff6d328fb866e64c1431fa55a794268), this line can be made simpler

2023-07-06 05:14 UTC, bogberry commented on indexer.Dockerfile
> +ENV ECONIA_ADDRESS=0x000000
What's the point of having default values here?

2023-07-20 02:53 UTC, bogberry approved these changes

2023-07-20 02:53 UTC, merged