[ECO-195] Update Pdocs for Python SDK: `pdoc -o docs econia_sdk`
econia-labs/econia pull request #375
Opened 2023-07-26 17:18 UTC by elliottdehn

Here I've just run the command in-title to generate the docsite for the Python SDK. Will add docstrings to all of the view functions at a later point in time.

2023-07-26 18:05 UTC, alnoki requested changes
Can you update the README for the Python SDK too?

I believe this will get included on the PyPI

2023-07-26 19:07 UTC, elliottdehn commented
> Can you update the README for the Python SDK too?
> 
> I believe this will get included on the PyPI

I just updated the README on this branch to what it is in #374 but it looks like this tool does not pick up the README.

2023-07-26 22:39 UTC, alnoki approved these changes

2023-07-26 22:39 UTC, merged

2023-07-27 03:31 UTC, bogberry commented
You can add the README to pdoc by including 

```
"""
.. include:: ../README.md
"""
```

to the top-level `__init__.py` as documented here:

<https://pdoc.dev/docs/pdoc.html>