[does not exist] does not work
econia-labs/econia pull request #386
Opened 2023-07-28 21:18 UTC by elliottdehn

2023-07-31 04:35 UTC, bogberry requested changes
Why not just use testnet APT?

2023-07-31 12:54 UTC, elliottdehn commented
> Why not just use testnet APT?

We're limited in how many APT we can request to mint, so it's much easier to be able to request lots fake APT than 1 APT at a time from a "real" faucet.

2023-07-31 15:20 UTC, alnoki requested changes
As just discussed during a team call, let's switch to `eAPT` ("Econia APT") and `eUSDC` ("Econia USDC") to avoid confusion that might arise from the `t` prefix (e.g. Tortuga liquid staking derivative)

2023-08-01 17:29 UTC, alnoki requested changes

2023-08-01 17:29 UTC, alnoki commented on src/python/sdk/examples/trade.py
> +COIN_TYPE_USDC = f"{FAUCET_ADDR}::example_usdc::ExampleUSDC"
For consistency how about `COIN_TYPE_EUSDC`?

2023-08-01 17:33 UTC, alnoki requested changes

2023-08-01 17:35 UTC, alnoki requested changes

2023-08-01 18:03 UTC, alnoki requested changes

2023-08-01 18:03 UTC, alnoki commented on src/move/faucet/sources/example_apt.move
> +    const NAME: vector<u8> = b"Example Aptos coin";
"Example Aptos Coin" (capital C)

2023-08-01 18:42 UTC, alnoki approved these changes

2023-08-02 05:11 UTC, bogberry approved these changes
Yup all good

2023-08-02 05:11 UTC, merged