Create cspell dictionary and add words to dictionary
econia-labs/econia pull request #387
Opened 2023-07-28 21:52 UTC by elliottdehn

Both Aptos and Econia appear often in our texts, but are detected as error words by cspell CLI. Let's fix that.

2023-07-31 04:44 UTC, qdrs commented
What an utter waste of time? Are company man hours being spent on stuff like this? Launch the product first

2023-07-31 06:46 UTC, bogberry requested changes
There seems to be a similiar list in `.vscode/settings.json`, so one of these should be removed in favor of the other.

2023-07-31 09:25 UTC, bogberry commented
But I don't think we should be running spellcheck on all of our code. Using names that aren't in the English language in code is pretty common, and I don't want to be adding words to a dictionary every time I do that

2023-07-31 17:03 UTC, alnoki commented
This PR touches on some recent DevOps discussions:

* Checks should ultimately be done in CI to reduce manual overhead (e.g. someone has to remember to run a check like a spellchecker)
* I do think that having a spellchecker is useful though, as it raises the degree of professionalism (Aptos' docs use a dictionary file and perform spellchecking on PRs)

2023-08-01 00:48 UTC, bogberry commented
We absolutely should not be running spellcheck in CI and rejecting PRs that have spelling errors. Using character strings that are not English words in code is EXTREMELY common, and we shouldn't be expected to add every single instance of a character string that isn't an English word into a dictionary to get a PR approved is ridiculous.

2023-08-01 14:06 UTC, elliottdehn commented
Closing this because it should be done by CI if at all.

2023-08-01 14:06 UTC, closed without merging