[ECO-225] Add glossary, prelimiary term set
econia-labs/econia pull request #399
Opened 2023-07-31 23:26 UTC by alnoki

This PR adds a glossary based on the Aptos glossary: https://aptos.dev/reference/glossary/

A select few terms are included to demonstrate formatting standards

2023-08-01 10:48 UTC, bogberry requested changes

2023-08-01 18:26 UTC, alnoki commented on doc/doc-site/README.md
>     brew install pnpm
@bogberry agreed, this diff is just a result of running `mdformat` to format the new glossary page, not an endorsement of the existing instructions

See https://linear.app/econia-labs/issue/ECO-324/make-doc-site-build-directions-os-agnostic

2023-08-02 04:58 UTC, bogberry commented on doc/doc-site/README.md
>     brew install pnpm
Ah okay

2023-08-02 04:58 UTC, bogberry approved these changes

2023-08-02 05:13 UTC, merged