[ECO-1153] add more documentation before publishing the rust crate
econia-labs/econia pull request #678
Opened 2024-01-29 16:05 UTC by CRBl69

Add some more Rust doc before publishing the crate to make reading the doc and using the crate more intuitive.

2024-01-29 19:42 UTC, alnoki requested changes
How about a minor README on how to generate the documentation and view?

2024-01-29 22:07 UTC, alnoki requested changes

2024-01-29 22:07 UTC, alnoki commented on src/rust/sdk/src/lib.rs
> +//! 3. There is no 3rd step.
How about taking this out?

2024-01-29 22:07 UTC, alnoki commented on src/rust/sdk/src/lib.rs
> +//!     - Or create a payload using helper functions from the [`entry`] module
How about something like?

"To use the SDK create an [`EconiaClient`], then either use it to get an [`EconiaViewClient`], or create a payload using helper functions from the [`entry`] module"

2024-01-29 22:07 UTC, alnoki commented on src/rust/sdk/src/view.rs
> +//! You can create a [`EconiaViewClient`] from a [`EconiaClient`](crate::EconiaClient) using the
"a" -> "an" in both cases in this line

2024-01-29 22:07 UTC, alnoki commented on src/rust/sdk/src/view.rs
> +//! There are also stand alone functions which do not need any blockchain state and compute
stand alone -> standalone

2024-01-29 22:07 UTC, alnoki commented on src/rust/sdk/src/view.rs
> +//! locally. Those do not need a [`EconiaViewClient`] to execute.
"a" -> "an"

2024-01-29 23:01 UTC, alnoki requested changes

2024-01-29 23:01 UTC, alnoki commented on src/rust/sdk/README.md
Admittedly I'm not too familiar with the `cargo doc` process, but still, I notice that when I run `cargo doc --open` the "crates" column has a ton of ineherited crates along the left side that are confusing in the context of the SDK

Is there a way to resolve this to point at an Aptos crate? Or perhaps to make the dependencies show up somewhere other than the `Crates` column navigator? Because I have to scroll down multiple pages to find the `econia_sdk` page

2024-01-31 07:57 UTC, CRBl69 commented on src/rust/sdk/README.md
I see what you mean, but I don't see how that is a problem since you are already on the `econia_sdk` page whenever you use `--open` or you click on the printed file path. And this won't be an issue when accessing [docs.rs](https://docs.rs/).

2024-01-31 07:59 UTC, CRBl69 commented on src/rust/sdk/README.md
> +You can check it out on the [docs.rs](https://docs.rs/) website, or locally, by running `cargo doc` and then opening the generated files (the one which's path is printed during doc compilation).
I see what you mean. Just FYI, this is what I see.

<img width="712" alt="image" src="https://github.com/econia-labs/econia/assets/67070716/70910de3-c0fa-4f5e-9eff-fce03e01628e">

2024-01-31 18:43 UTC, alnoki approved these changes

2024-01-31 18:43 UTC, merged